const { Animal } = require('../models');

const animalData = [
  {
    name: 'Ellie',
    type: 'dog',
    weight: '40',
    breed: 'great-pyranese',
    sex: 'female',
    fixed: true,
    color: { 'colors': ['brown', 'white'] },
    date_lost: '2022-09-08',
    date_found: null,
    city: 'newark',
    animal_id: 1,
  },
  {
    name: 'Gracie',
    type: 'dog',
    weight: '50',
    breed: 'mixed',
    sex: 'female',
    fixed: true,
    color: { 'colors': ['black', 'white'] },
    date_lost: '2022-07-16',
    date_found: null,
    city: 'heath',
    animal_id: 2,
  },
  {
    name: 'Mozzerella Cheese (Mozzie)',
    type: 'cat',
    weight: '12',
    breed: null,
    sex: 'female',
    fixed: true,
    color: { 'colors': ['black', 'white'] },
    date_lost: '2022-09-02',
    date_found: null,
    city: 'columbus',
    animal_id: 3,
  },
  {
    name: 'Winnie',
    type: 'cat',
    weight: '8',
    breed: 'tabby',
    sex: 'female',
    fixed: true,
    color: { 'colors': ['gray', 'white', 'black','tan'] },
    date_lost: '2022-04-16',
    date_found: null,
    city: 'new york',
    animal_id: 3,
  },
  {
    name: 'Tater',
    type: 'gerbil',
    weight: '0.1',
    breed: null,
    sex: 'male',
    fixed: false,
    color: { 'colors': ['tan', 'white'] },
    date_lost: '2022-05-12',
    date_found: null,
    city: 'new albany',
    animal_id: 4,
  },
  {
    name: 'Tot',
    type: 'gerbil',
    weight: '0.1',
    breed: null,
    sex: 'male',
    fixed: false,
    color: { 'colors': ['tan', 'white'] },
    date_lost: '2022-05-15',
    date_found: null,
    city: 'lancaster',
    animal_id: 5,
  },
];

const seedAnimal = () => Animal.bulkCreate(animalData);

module.exports = seedAnimal;
